# Generated by Django 5.0.3 on 2024-03-21 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_convert_quantity_to_charfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='quantity',
            field=models.CharField(max_length=200),
        ),
    ]
